services:
  api:
    container_name: api
    image: yifattih/rmr-projection:api
    ports:
      - "8001:8000"
  ui:
    container_name: ui
    build:
      context: service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"