---
name: Build and Push to Docker Hub

on:
    push:
        branches:
            - 'dev'

env:
    SERVICE_NAME: 'ui'

jobs:
    ci-pipeline:
      name: Run reusable CI pipeline
      uses: ./.github/workflows/ci.yml
      with:
        external_call: true
        env_vars: |
          SONAR_ORGANIZATION=${{ vars.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY=${{ vars.SONAR_PROJECT_KEY }}
      secrets: inherit

    build-push:
        name: Build Image and Push to Docker Hub
        runs-on: ubuntu-latest
        environment: development
        needs: ci-pipeline
        permissions: write-all
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
      
            - name: Docker Login
              uses: docker/login-action@v3.3.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.10.0

            - name: Build and push
              uses: docker/build-push-action@v6.15.0
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.SERVICE_NAME }}
