---
name: Docker Hub Courier

on:
  pull_request:
    types:
      - closed
    branches:
      - 'dev'

env:
  SERVICE_NAME: 'ui'

jobs:
  docker:
    name: Build Image and Push to Docker Hub
    runs-on: ubuntu-latest
    environment: development
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          context: service
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.SERVICE_NAME }}