name: Semantic Release

on:
    pull_request:
        types:
            - closed
        branches:
            - main
            - alpha
    push:
        branches:
            - main
            - alpha

jobs:
    ci-pipeline:
        name: Run reusable CI pipeline
        uses: ./.github/workflows/ci.yml
        with:
            external_call: true
            env_vars: |
                SONAR_ORGANIZATION=${{ vars.SONAR_ORGANIZATION }}
                SONAR_PROJECT_KEY=${{ vars.SONAR_PROJECT_KEY }}
        secrets: inherit

    semantic-release:
        name: Semantic Release
        runs-on: ubuntu-latest
        needs: ci-pipeline
        permissions: write-all
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
            IMAGE_TAG: ${{ steps.semantic.outputs.new_release_version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4.1.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                node-version: "lts/*"

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4.2.0
              id: semantic
              with:
                semantic_version: 24.2.3
                branches: |
                    [
                        '+([0-9])?(.{+([0-9]),x}).x',
                        'main',
                        {
                            name: 'alpha',
                            prerelease: true
                        }
                    ]
                extra_plugins: |
                    @semantic-release/commit-analyzer
                    @semantic-release/release-notes-generator
                    @semantic-release/github
                    @semantic-release/changelog
                    @semantic-release/git
